// <auto-generated />
namespace ReadComic.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class edit_loaiTruyen : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(edit_loaiTruyen));
        
        string IMigrationMetadata.Id
        {
            get { return "201903250401398_edit_loaiTruyen"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
