namespace ReadComic.Database.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class editdb1 : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.BinhLuan", "Created_at", c => c.DateTime());
            AddColumn("dbo.BinhLuan", "Created_by", c => c.Int(nullable: false));
            AddColumn("dbo.BinhLuan", "Updated_at", c => c.DateTime());
            AddColumn("dbo.BinhLuan", "Updated_by", c => c.Int());
            AddColumn("dbo.BinhLuan", "DelFlag", c => c.Boolean(nullable: false));
            AddColumn("dbo.TaiKhoan", "Created_at", c => c.DateTime());
            AddColumn("dbo.TaiKhoan", "Created_by", c => c.Int(nullable: false));
            AddColumn("dbo.TaiKhoan", "Updated_at", c => c.DateTime());
            AddColumn("dbo.TaiKhoan", "Updated_by", c => c.Int());
            AddColumn("dbo.TaiKhoan", "DelFlag", c => c.Boolean(nullable: false));
            AddColumn("dbo.Bookmark", "Created_at", c => c.DateTime());
            AddColumn("dbo.Bookmark", "Created_by", c => c.Int(nullable: false));
            AddColumn("dbo.Bookmark", "Updated_at", c => c.DateTime());
            AddColumn("dbo.Bookmark", "Updated_by", c => c.Int());
            AddColumn("dbo.Bookmark", "DelFlag", c => c.Boolean(nullable: false));
            AddColumn("dbo.Chuong", "Created_at", c => c.DateTime());
            AddColumn("dbo.Chuong", "Created_by", c => c.Int(nullable: false));
            AddColumn("dbo.Chuong", "Updated_at", c => c.DateTime());
            AddColumn("dbo.Chuong", "Updated_by", c => c.Int());
            AddColumn("dbo.Chuong", "DelFlag", c => c.Boolean(nullable: false));
            AddColumn("dbo.Truyen", "Created_at", c => c.DateTime());
            AddColumn("dbo.Truyen", "Created_by", c => c.Int(nullable: false));
            AddColumn("dbo.Truyen", "Updated_at", c => c.DateTime());
            AddColumn("dbo.Truyen", "Updated_by", c => c.Int());
            AddColumn("dbo.Truyen", "DelFlag", c => c.Boolean(nullable: false));
            AddColumn("dbo.ChuKyPhatHanh", "Created_at", c => c.DateTime());
            AddColumn("dbo.ChuKyPhatHanh", "Created_by", c => c.Int(nullable: false));
            AddColumn("dbo.ChuKyPhatHanh", "Updated_at", c => c.DateTime());
            AddColumn("dbo.ChuKyPhatHanh", "Updated_by", c => c.Int());
            AddColumn("dbo.ChuKyPhatHanh", "DelFlag", c => c.Boolean(nullable: false));
            AddColumn("dbo.DanhGiaTruyen", "Created_at", c => c.DateTime());
            AddColumn("dbo.DanhGiaTruyen", "Created_by", c => c.Int(nullable: false));
            AddColumn("dbo.DanhGiaTruyen", "Updated_at", c => c.DateTime());
            AddColumn("dbo.DanhGiaTruyen", "Updated_by", c => c.Int());
            AddColumn("dbo.DanhGiaTruyen", "DelFlag", c => c.Boolean(nullable: false));
            AddColumn("dbo.LoaiTruyen", "Created_at", c => c.DateTime());
            AddColumn("dbo.LoaiTruyen", "Created_by", c => c.Int(nullable: false));
            AddColumn("dbo.LoaiTruyen", "Updated_at", c => c.DateTime());
            AddColumn("dbo.LoaiTruyen", "Updated_by", c => c.Int());
            AddColumn("dbo.LoaiTruyen", "DelFlag", c => c.Boolean(nullable: false));
            AddColumn("dbo.LuuTacGia", "Created_at", c => c.DateTime());
            AddColumn("dbo.LuuTacGia", "Created_by", c => c.Int(nullable: false));
            AddColumn("dbo.LuuTacGia", "Updated_at", c => c.DateTime());
            AddColumn("dbo.LuuTacGia", "Updated_by", c => c.Int());
            AddColumn("dbo.LuuTacGia", "DelFlag", c => c.Boolean(nullable: false));
            AddColumn("dbo.TacGia", "Created_at", c => c.DateTime());
            AddColumn("dbo.TacGia", "Created_by", c => c.Int(nullable: false));
            AddColumn("dbo.TacGia", "Updated_at", c => c.DateTime());
            AddColumn("dbo.TacGia", "Updated_by", c => c.Int());
            AddColumn("dbo.TacGia", "DelFlag", c => c.Boolean(nullable: false));
            AddColumn("dbo.LuuTheLoai", "Created_at", c => c.DateTime());
            AddColumn("dbo.LuuTheLoai", "Created_by", c => c.Int(nullable: false));
            AddColumn("dbo.LuuTheLoai", "Updated_at", c => c.DateTime());
            AddColumn("dbo.LuuTheLoai", "Updated_by", c => c.Int());
            AddColumn("dbo.LuuTheLoai", "DelFlag", c => c.Boolean(nullable: false));
            AddColumn("dbo.TheLoai", "Created_at", c => c.DateTime());
            AddColumn("dbo.TheLoai", "Created_by", c => c.Int(nullable: false));
            AddColumn("dbo.TheLoai", "Updated_at", c => c.DateTime());
            AddColumn("dbo.TheLoai", "Updated_by", c => c.Int());
            AddColumn("dbo.TheLoai", "DelFlag", c => c.Boolean(nullable: false));
            AddColumn("dbo.NhomDich", "Created_at", c => c.DateTime());
            AddColumn("dbo.NhomDich", "Created_by", c => c.Int(nullable: false));
            AddColumn("dbo.NhomDich", "Updated_at", c => c.DateTime());
            AddColumn("dbo.NhomDich", "Updated_by", c => c.Int());
            AddColumn("dbo.NhomDich", "DelFlag", c => c.Boolean(nullable: false));
            AddColumn("dbo.ThongTinNguoiDung", "Created_at", c => c.DateTime());
            AddColumn("dbo.ThongTinNguoiDung", "Created_by", c => c.Int(nullable: false));
            AddColumn("dbo.ThongTinNguoiDung", "Updated_at", c => c.DateTime());
            AddColumn("dbo.ThongTinNguoiDung", "Updated_by", c => c.Int());
            AddColumn("dbo.ThongTinNguoiDung", "DelFlag", c => c.Boolean(nullable: false));
            AddColumn("dbo.TrangThaiTruyen", "Created_at", c => c.DateTime());
            AddColumn("dbo.TrangThaiTruyen", "Created_by", c => c.Int(nullable: false));
            AddColumn("dbo.TrangThaiTruyen", "Updated_at", c => c.DateTime());
            AddColumn("dbo.TrangThaiTruyen", "Updated_by", c => c.Int());
            AddColumn("dbo.TrangThaiTruyen", "DelFlag", c => c.Boolean(nullable: false));
            AddColumn("dbo.PhanQuyen", "Created_at", c => c.DateTime());
            AddColumn("dbo.PhanQuyen", "Created_by", c => c.Int(nullable: false));
            AddColumn("dbo.PhanQuyen", "Updated_at", c => c.DateTime());
            AddColumn("dbo.PhanQuyen", "Updated_by", c => c.Int());
            AddColumn("dbo.PhanQuyen", "DelFlag", c => c.Boolean(nullable: false));
            AddColumn("dbo.VaiTro", "Created_at", c => c.DateTime());
            AddColumn("dbo.VaiTro", "Created_by", c => c.Int(nullable: false));
            AddColumn("dbo.VaiTro", "Updated_at", c => c.DateTime());
            AddColumn("dbo.VaiTro", "Updated_by", c => c.Int());
            AddColumn("dbo.VaiTro", "DelFlag", c => c.Boolean(nullable: false));
            AddColumn("dbo.Token", "Created_at", c => c.DateTime());
            AddColumn("dbo.Token", "Created_by", c => c.Int(nullable: false));
            AddColumn("dbo.Token", "Updated_at", c => c.DateTime());
            AddColumn("dbo.Token", "Updated_by", c => c.Int());
            AddColumn("dbo.Token", "DelFlag", c => c.Boolean(nullable: false));
            AddColumn("dbo.TrangThaiTaiKhoan", "Created_at", c => c.DateTime());
            AddColumn("dbo.TrangThaiTaiKhoan", "Created_by", c => c.Int(nullable: false));
            AddColumn("dbo.TrangThaiTaiKhoan", "Updated_at", c => c.DateTime());
            AddColumn("dbo.TrangThaiTaiKhoan", "Updated_by", c => c.Int());
            AddColumn("dbo.TrangThaiTaiKhoan", "DelFlag", c => c.Boolean(nullable: false));
            AddColumn("dbo.ErrorMsg", "Created_at", c => c.DateTime());
            AddColumn("dbo.ErrorMsg", "Created_by", c => c.Int(nullable: false));
            AddColumn("dbo.ErrorMsg", "Updated_at", c => c.DateTime());
            AddColumn("dbo.ErrorMsg", "Updated_by", c => c.Int());
            AddColumn("dbo.ErrorMsg", "DelFlag", c => c.Boolean(nullable: false));
            AddColumn("dbo.Quyen", "Created_at", c => c.DateTime());
            AddColumn("dbo.Quyen", "Created_by", c => c.Int(nullable: false));
            AddColumn("dbo.Quyen", "Updated_at", c => c.DateTime());
            AddColumn("dbo.Quyen", "Updated_by", c => c.Int());
            AddColumn("dbo.Quyen", "DelFlag", c => c.Boolean(nullable: false));
        }
        
        public override void Down()
        {
            DropColumn("dbo.Quyen", "DelFlag");
            DropColumn("dbo.Quyen", "Updated_by");
            DropColumn("dbo.Quyen", "Updated_at");
            DropColumn("dbo.Quyen", "Created_by");
            DropColumn("dbo.Quyen", "Created_at");
            DropColumn("dbo.ErrorMsg", "DelFlag");
            DropColumn("dbo.ErrorMsg", "Updated_by");
            DropColumn("dbo.ErrorMsg", "Updated_at");
            DropColumn("dbo.ErrorMsg", "Created_by");
            DropColumn("dbo.ErrorMsg", "Created_at");
            DropColumn("dbo.TrangThaiTaiKhoan", "DelFlag");
            DropColumn("dbo.TrangThaiTaiKhoan", "Updated_by");
            DropColumn("dbo.TrangThaiTaiKhoan", "Updated_at");
            DropColumn("dbo.TrangThaiTaiKhoan", "Created_by");
            DropColumn("dbo.TrangThaiTaiKhoan", "Created_at");
            DropColumn("dbo.Token", "DelFlag");
            DropColumn("dbo.Token", "Updated_by");
            DropColumn("dbo.Token", "Updated_at");
            DropColumn("dbo.Token", "Created_by");
            DropColumn("dbo.Token", "Created_at");
            DropColumn("dbo.VaiTro", "DelFlag");
            DropColumn("dbo.VaiTro", "Updated_by");
            DropColumn("dbo.VaiTro", "Updated_at");
            DropColumn("dbo.VaiTro", "Created_by");
            DropColumn("dbo.VaiTro", "Created_at");
            DropColumn("dbo.PhanQuyen", "DelFlag");
            DropColumn("dbo.PhanQuyen", "Updated_by");
            DropColumn("dbo.PhanQuyen", "Updated_at");
            DropColumn("dbo.PhanQuyen", "Created_by");
            DropColumn("dbo.PhanQuyen", "Created_at");
            DropColumn("dbo.TrangThaiTruyen", "DelFlag");
            DropColumn("dbo.TrangThaiTruyen", "Updated_by");
            DropColumn("dbo.TrangThaiTruyen", "Updated_at");
            DropColumn("dbo.TrangThaiTruyen", "Created_by");
            DropColumn("dbo.TrangThaiTruyen", "Created_at");
            DropColumn("dbo.ThongTinNguoiDung", "DelFlag");
            DropColumn("dbo.ThongTinNguoiDung", "Updated_by");
            DropColumn("dbo.ThongTinNguoiDung", "Updated_at");
            DropColumn("dbo.ThongTinNguoiDung", "Created_by");
            DropColumn("dbo.ThongTinNguoiDung", "Created_at");
            DropColumn("dbo.NhomDich", "DelFlag");
            DropColumn("dbo.NhomDich", "Updated_by");
            DropColumn("dbo.NhomDich", "Updated_at");
            DropColumn("dbo.NhomDich", "Created_by");
            DropColumn("dbo.NhomDich", "Created_at");
            DropColumn("dbo.TheLoai", "DelFlag");
            DropColumn("dbo.TheLoai", "Updated_by");
            DropColumn("dbo.TheLoai", "Updated_at");
            DropColumn("dbo.TheLoai", "Created_by");
            DropColumn("dbo.TheLoai", "Created_at");
            DropColumn("dbo.LuuTheLoai", "DelFlag");
            DropColumn("dbo.LuuTheLoai", "Updated_by");
            DropColumn("dbo.LuuTheLoai", "Updated_at");
            DropColumn("dbo.LuuTheLoai", "Created_by");
            DropColumn("dbo.LuuTheLoai", "Created_at");
            DropColumn("dbo.TacGia", "DelFlag");
            DropColumn("dbo.TacGia", "Updated_by");
            DropColumn("dbo.TacGia", "Updated_at");
            DropColumn("dbo.TacGia", "Created_by");
            DropColumn("dbo.TacGia", "Created_at");
            DropColumn("dbo.LuuTacGia", "DelFlag");
            DropColumn("dbo.LuuTacGia", "Updated_by");
            DropColumn("dbo.LuuTacGia", "Updated_at");
            DropColumn("dbo.LuuTacGia", "Created_by");
            DropColumn("dbo.LuuTacGia", "Created_at");
            DropColumn("dbo.LoaiTruyen", "DelFlag");
            DropColumn("dbo.LoaiTruyen", "Updated_by");
            DropColumn("dbo.LoaiTruyen", "Updated_at");
            DropColumn("dbo.LoaiTruyen", "Created_by");
            DropColumn("dbo.LoaiTruyen", "Created_at");
            DropColumn("dbo.DanhGiaTruyen", "DelFlag");
            DropColumn("dbo.DanhGiaTruyen", "Updated_by");
            DropColumn("dbo.DanhGiaTruyen", "Updated_at");
            DropColumn("dbo.DanhGiaTruyen", "Created_by");
            DropColumn("dbo.DanhGiaTruyen", "Created_at");
            DropColumn("dbo.ChuKyPhatHanh", "DelFlag");
            DropColumn("dbo.ChuKyPhatHanh", "Updated_by");
            DropColumn("dbo.ChuKyPhatHanh", "Updated_at");
            DropColumn("dbo.ChuKyPhatHanh", "Created_by");
            DropColumn("dbo.ChuKyPhatHanh", "Created_at");
            DropColumn("dbo.Truyen", "DelFlag");
            DropColumn("dbo.Truyen", "Updated_by");
            DropColumn("dbo.Truyen", "Updated_at");
            DropColumn("dbo.Truyen", "Created_by");
            DropColumn("dbo.Truyen", "Created_at");
            DropColumn("dbo.Chuong", "DelFlag");
            DropColumn("dbo.Chuong", "Updated_by");
            DropColumn("dbo.Chuong", "Updated_at");
            DropColumn("dbo.Chuong", "Created_by");
            DropColumn("dbo.Chuong", "Created_at");
            DropColumn("dbo.Bookmark", "DelFlag");
            DropColumn("dbo.Bookmark", "Updated_by");
            DropColumn("dbo.Bookmark", "Updated_at");
            DropColumn("dbo.Bookmark", "Created_by");
            DropColumn("dbo.Bookmark", "Created_at");
            DropColumn("dbo.TaiKhoan", "DelFlag");
            DropColumn("dbo.TaiKhoan", "Updated_by");
            DropColumn("dbo.TaiKhoan", "Updated_at");
            DropColumn("dbo.TaiKhoan", "Created_by");
            DropColumn("dbo.TaiKhoan", "Created_at");
            DropColumn("dbo.BinhLuan", "DelFlag");
            DropColumn("dbo.BinhLuan", "Updated_by");
            DropColumn("dbo.BinhLuan", "Updated_at");
            DropColumn("dbo.BinhLuan", "Created_by");
            DropColumn("dbo.BinhLuan", "Created_at");
        }
    }
}
